### Get all
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsImlkIjoiNjM2MDllNDdmM2E0NzVjNzRjYjY4NjdlIiwiaWF0IjoxNjY3Mjc2MzY4LCJleHAiOjE2NjcyNzk5Njh9.iLPD4PzCZMinDxf2qLL_BU8gqLt0CIJ1exNLCa42qBw

{
    "title": "111",
    "author": "111",
    "url": "1.com",
    "likes": 1
}

###
DELETE http://localhost:3003/api/blogs/635b1c22eff27b2a40df117a
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsImlkIjoiNjM1YjBlNjJiYmIwMDg2ZDcwYjU3ZjRkIiwiaWF0IjoxNjY2OTE0OTcxLCJleHAiOjE2NjY5MTg1NzF9.gjJjhSYsHhsfRfwXmdlAqYhhXIPYlgUnLxQ-dtj-S9E

###
PUT http://localhost:3003/api/blogs/635e2069569a9c292272d095
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsImlkIjoiNjM1ZTIwMjE1NjlhOWMyOTIyNzJkMDkxIiwiaWF0IjoxNjY3MTQ2MDI4LCJleHAiOjE2NjcxNDk2Mjh9.9hiCFZZmEwj6RqiZTCksoZqsRDucB73CBpejOlvbJeU

{
    "title": "111",
    "author": "111",
    "url": "1.com",
    "likes": 2
}